### ISSUE TITLE
how to find out $containerUrl

### ISSUE THREAD

**Issue by myaMemo** [norcino/docker-dotnet-core-api-qnap-nas#3]
Hi, this is not an issue but a question: Can you please tell me how i can find out the URL of my QNAP-Nas to fill in in variable $containerUrl of build.ps1? 
I'm a newbie regarding docker and qnap container station so please bare me for this question. 
Thank you in advance, 
memo

**Comment by norcino** [comment]
Hi @myaMemo in my case the url is:
$containerUrl = "tcp://nas.home:2376"
Where **nas.home** is a local hostname my router resolve to the NAS IP Address. So if you don't have a local hostname use the IP address used by your NAS.
If you can you should make sure the router DHCP you use at home, reserve the same IP Address for your NAS's MAC Address.

Note it is a while I don't work on this project and lately QNAP update the Container Station, especially on the storage side, so it might not work properly anymore this example.
I will go back to this soon and if necessary update it, I first need to finish another project.
